// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_Folha.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("API.Models.FolhaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ano")
                        .HasColumnType("TEXT");

                    b.Property<string>("cpfFuncionario")
                        .HasColumnType("TEXT");

                    b.Property<int?>("funcionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("impostoFGTS")
                        .HasColumnType("REAL");

                    b.Property<double>("impostoINSS")
                        .HasColumnType("REAL");

                    b.Property<double>("impostoRenda")
                        .HasColumnType("REAL");

                    b.Property<string>("mes")
                        .HasColumnType("TEXT");

                    b.Property<double>("quantidaDedeHoras")
                        .HasColumnType("REAL");

                    b.Property<double>("salarioBruto")
                        .HasColumnType("REAL");

                    b.Property<double>("salarioLiquido")
                        .HasColumnType("REAL");

                    b.Property<double>("valorHora")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("funcionarioId");

                    b.ToTable("Folhas");
                });

            modelBuilder.Entity("API.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Salario")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("API.Models.FolhaPagamento", b =>
                {
                    b.HasOne("API.Models.Funcionario", "funcionario")
                        .WithMany()
                        .HasForeignKey("funcionarioId");

                    b.Navigation("funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
